export const mapKeyToHeading = (key: string): string => {
  const mappings: { [key: string]: string } = {
    YEA4: "Year",
    JRNO: "Journal Number",
    JSNO: "Journal Series Number",
    TRCD: "Transaction Code",
    SPYN: "Supplier Payment Year",
    SUNO: "Supplier Number",
    SINO: "Supplier Invoice Number",
    INYR: "Invoice Year",
    VSER: "Version Series",
    VONO: "Voucher Number",
    IVTP: "Invoice Type",
    TDSC: "Transaction Description",
    APCD: "Authorized User",
    IVBL: "Invoice Balance",
    BLBY: "Billed By",
    BLDT: "Billing Date",
    APRV: "Approval Status",
    SUCL: "Supplier Classification",
    BKID: "Bank ID",
    CUCD: "Currency Code",
    CRTP: "Currency Rate Type",
    ARAT: "Applicable Rate",
    CUAM: "Currency Amount",
    DCAM: "Discount Amount",
    VTAM: "VAT Amount",
    IVDT: "Invoice Date",
    DUDT: "Due Date",
    ACDT: "Accounting Date",
    TECD: "Tax Code",
    PYTP: "Payment Type",
    PYME: "Payment Method",
    TEPY: "Terms of Payment",
    RECO: "Record Count",
    REDE: "Redemption Date",
    SLOP: "Slope",
    PYST: "Payment Status",
    PYRS: "Payers",
    ARCD: "Archive Code",
    ENME: "Entry Name",
    TXID: "Tax ID",
    TDCD: "Tax Deduction Code",
    RGDT: "Registration Date",
    RGTM: "Registration Time",
    LMDT: "Last Modified Date",
    CHNO: "Change Number",
    CHID: "Change ID",
    DEDA: "Deduction Date",
    LMTS: "Limit Seconds",
    IVCL: "Invoice Class",
    ACAM: "Account Amount",
    PCUA: "Primary Currency Amount",
    PAMT: "Paid Amount",
    OCUA: "Original Currency Amount",
    OAMT: "Original Amount",
    TBCU: "Taxable Base Currency",
    TBAM: "Taxable Base Amount",
    TXCU: "Tax Currency",
    TXAM: "Tax Amount",
    CDCU: "Credit/Debit Currency",
    LOCD: "Currency",
    CDAM: "Credit/Debit Amount",
    PAIN: "Pain",
    WRCU: "Warranty Currency",
    WRAM: "Warranty Amount",
    ROCU: "Return Currency",
    ROAM: "Return Amount",
    TDS1: "Tax Deduction Source 1",
    F1PK01: "Invoice Date",
    F1PK02: "Supplier Number",
    F1PK03: "Supplier Invoice Number",
    F1A030: "Status",
    F1A130: "User Id",
    F1A230: "Event Description",
    F1A330: "Event timestamp",
    F1A530: "Comment",
    id: "Identifier",
  };

  return mappings[key] || key; // Fallback to key if no mapping exists
};
